// Generated by CoffeeScript 1.8.0
var $button, cleanSource;

cleanSource = function(html) {
  var indentSize, lines, re;
  lines = html.split('\n');
  lines.shift();
  lines.splice(-1, 1);
  indentSize = lines[0].length - lines[0].trim().length;
  re = new RegExp(" {" + indentSize + "}");
  lines = lines.map(function(line) {
    if (line.match(re)) {
      line = line.substring(indentSize);
    }
    return line;
  });
  lines = lines.join("\n");
  return lines;
};

$button = $("<div id='source-button' class='btn btn-primary btn-xs'>&lt; &gt;</div>").click(function() {
  var index;
  index = $('.bs-component').index($(this).parent());
  return $.get(window.location.href, function(data) {
    var html;
    html = $(data).find('.bs-component').eq(index).html();
    html = clearnSource(html);
    $('#source-modal pre').text(html);
    return $('#source-modal').modal();
  });
});

$('.bs-component [data-toggle="popover"]').popover();

$('.bs-component [data-toggle="tooltip"]').tooltip();

$(".bs-component").hover(function() {
  return $(this).append($button);
}, function() {
  return $button.hide();
});

$(".icons-material .icon").each(function() {
  return $(this).after("<br><br><code>" + $(this).attr("class").replace("icon ", "") + "</code>");
});
